// src/templates.js

const templates = [
    {
        id: 'template1',
        name: 'Minimalist',
        category: 'Minimalist',
        layout: 'horizontal',
        style: {
            fontFamily: 'Arial',
            fontSize: 14,
            fontColor: '#000000',
            primaryColor: '#000000',
            backgroundColor: '#FFFFFF',
        },
        components: ['name', 'jobTitle', 'companyName', 'emailAddress', 'socialLinks'],
    },
    {
        id: 'template2',
        name: 'Corporate',
        category: 'Corporate',
        layout: 'vertical',
        style: {
            fontFamily: 'Times New Roman',
            fontSize: 12,
            fontColor: '#333333',
            primaryColor: '#000080',
            backgroundColor: '#F0F0F0',
        },
        components: ['name', 'jobTitle', 'companyName', 'emailAddress', 'phoneNumber', 'socialLinks'],
    },
    // Add more templates up to 10
    {
        id: 'template3',
        name: 'Modern',
        category: 'Modern',
        layout: 'horizontal',
        style: {
            fontFamily: 'Helvetica',
            fontSize: 13,
            fontColor: '#222222',
            primaryColor: '#FF5722',
            backgroundColor: '#FFFFFF',
        },
        components: ['profileImage', 'name', 'jobTitle', 'companyName', 'emailAddress', 'websiteURL', 'socialLinks'],
    },
    {
        id: 'template4',
        name: 'Creative',
        category: 'Creative',
        layout: 'vertical',
        style: {
            fontFamily: 'Georgia',
            fontSize: 14,
            fontColor: '#444444',
            primaryColor: '#9C27B0',
            backgroundColor: '#FFFFFF',
        },
        components: ['name', 'jobTitle', 'emailAddress', 'phoneNumber', 'socialLinks'],
    },
    {
        id: 'template5',
        name: 'Elegant',
        category: 'Minimalist',
        layout: 'horizontal',
        style: {
            fontFamily: 'Palatino',
            fontSize: 15,
            fontColor: '#000000',
            primaryColor: '#795548',
            backgroundColor: '#FAFAFA',
        },
        components: ['profileImage', 'name', 'jobTitle', 'companyName', 'emailAddress'],
    },
    {
        id: 'template6',
        name: 'Bold',
        category: 'Corporate',
        layout: 'horizontal',
        style: {
            fontFamily: 'Verdana',
            fontSize: 14,
            fontColor: '#FFFFFF',
            primaryColor: '#2196F3',
            backgroundColor: '#2196F3',
        },
        components: ['name', 'jobTitle', 'emailAddress', 'phoneNumber', 'websiteURL'],
    },
    {
        id: 'template7',
        name: 'Classic',
        category: 'Modern',
        layout: 'vertical',
        style: {
            fontFamily: 'Courier New',
            fontSize: 12,
            fontColor: '#000000',
            primaryColor: '#607D8B',
            backgroundColor: '#ECEFF1',
        },
        components: ['name', 'jobTitle', 'companyName', 'emailAddress'],
    },
    {
        id: 'template8',
        name: 'Vibrant',
        category: 'Creative',
        layout: 'horizontal',
        style: {
            fontFamily: 'Trebuchet MS',
            fontSize: 13,
            fontColor: '#FFFFFF',
            primaryColor: '#E91E63',
            backgroundColor: '#E91E63',
        },
        components: ['name', 'jobTitle', 'emailAddress', 'socialLinks'],
    },
    {
        id: 'template9',
        name: 'Professional',
        category: 'Corporate',
        layout: 'horizontal',
        style: {
            fontFamily: 'Lucida Sans',
            fontSize: 13,
            fontColor: '#333333',
            primaryColor: '#4CAF50',
            backgroundColor: '#FFFFFF',
        },
        components: ['profileImage', 'name', 'jobTitle', 'companyName', 'emailAddress', 'phoneNumber', 'websiteURL'],
    },
    {
        id: 'template10',
        name: 'Simple',
        category: 'Minimalist',
        layout: 'vertical',
        style: {
            fontFamily: 'Tahoma',
            fontSize: 12,
            fontColor: '#000000',
            primaryColor: '#000000',
            backgroundColor: '#FFFFFF',
        },
        components: ['name', 'emailAddress', 'socialLinks'],
    },
];

export default templates;
